name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests without LLM integration
      run: pytest -v -m "not llm_integration"
#    - name: Run all tests including LLM integration
#      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#      env:
#        DEFAULT_API_KEY: ${{ secrets.DEFAULT_API_KEY }}
#        DEFAULT_BASE_URL: ${{ secrets.DEFAULT_BASE_URL }}
#        DEFAULT_MODEL: ${{ secrets.DEFAULT_MODEL }}
#      run: pytest -v
